### PR TITLE
Rename project to Mediapipe

### LINKED ISSUE #24: Rename project to Mediapipe
Now that we're close to being released, at post-Debut for Vignette, we would want to rename it as `Mediapipe` simply instead, then focus our attention in merging our work with the main MediaPipeUnity project and just focus as one group.

As such here's some of the TODOs we can do at the Encore roadmap:

- [ ] rename the project to simply `Mediapipe`.

### PR DESCRIPTION
**Pull request by adryzz**
Closes #24 

## Changes

- [x] Rename main managed code
- [x] Rename all autogenerated code
- [x] Rename tests
- [x] Rename examples
- [x] Rename project
- [x] Check for build issues

### CODE REVIEW

**Comment by adryzz** [comment]
Wait it changed all the newlines... lemme fix that

**Comment by sr229** [comment]
You might need to rebase this or redo this entire PR again @adryzz. This has diverged from the repo for a while now.

**Comment by Speykious** [comment]
Maybe my `CharSet` marshallings weren't desirable, despite the warnings of my editor.
We'll have to investigate this for the rewrite.

**Review by Speykious — DISMISSED** [review]
At this point, Akihabara is pretty much renamed. So LGTM.
Let's wait until the tests succeed and then merge this.
I guess we should now work on the rewrite.

**Comment by Speykious** [comment]
Oops, since we use the package references, we now have to use the runtime arguments for tests. I forgor :skull:

**Comment by adryzz** [comment]
doesn't matter, we know it runs lol

**Comment by sr229** [comment]
Closing in favor of Project Ayase.

**Pull request closed without merging**
