### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by adryzz**
Yeah some code cleanup

- [x] Waiting on #16 to be merged

Will probably give lots of conflicts...

Fixed stuff:

- [x] Removed unnecessary usings
- [x] Used consistent naming
- [x] Removed unnecessary casts
- [x] Removed unnecessary `this.`
- [x] Ordered the usings
- [x] Probably more but i can't remember.

### CODE REVIEW

**Comment by sr229** [comment]
You might want to fix CI to compile libmediapipe before merge this.

**Comment by Speykious** [comment]
There are still major bugs highlighted by the now complete unit tests that have yet to be fixed. We will need to fix all that before doing this final code cleanup. Once we get to do this code cleanup, I think it should be a different pull request that just adds a few commits after the merged fixes to avoid any merge conflicts.

**Comment by adryzz** [comment]
> There are still major bugs highlighted by the now complete unit tests that have yet to be fixed. We will need to fix all that before doing this final code cleanup. Once we get to do this code cleanup, I think it should be a different pull request that just adds a few commits after the merged fixes to avoid any merge conflicts.

Doing the fixes after the code cleanup is better imo... You will have better code to work with.

**Comment by Speykious** [comment]
The reason I want to do the code cleanup *after* the fixes is because while the code might be better to work with, we might just make some inconsistencies here and there and I would prefer not to do a second cleanup just in case...

**Comment by sr229** [comment]
> The reason I want to do the code cleanup _after_ the fixes is because while the code might be better to work with, we might just make some inconsistencies here and there and I would prefer not to do a second cleanup just in case...

This is out of scope if that's the case so just make another PR instead of blocking this one.

**Review by sr229 — CHANGES_REQUESTED** [review]
Before we merge this, fix CI then I'll approve this for auto-merge.

**Comment by adryzz** [comment]
Yes, i am working on CI with some people smarter than me... slowly finding the issue
image

**Pull request closed without merging**
