### PR TITLE
Added more protofiles

### PR DESCRIPTION
**Pull request by ym56**
Notes: 
Make sure that all of the packages in the .proto files are aligned

List of .cs files and the corresponding .proto files added: 
Detection
Landmark
LocationData
MatrixData
ModelMatrix
Rasterization
Rect
StickerBuffer

Part of FaceGeometry stuff.
FaceGeometry
Mesh3D

### CODE REVIEW

**Review by Speykious — CHANGES_REQUESTED** [review]
Is that all the proto files we need? If so, it would be nice to organize them inside the `protofiles` folder the same way they are inside of the `mediapipe` repository, like `face_geometry` going into `protofiles/modules/` and `landmark.proto` going into `protofiles/framework/formats/`.

**Comment by ym56** [comment]
I have no idea if this is all the proto files that we need, but categorizing them is a good idea either way

**Comment by Speykious** [comment]
I think it's a good idea to do it in this PR, as the protofiles will produce the same code whether we reorganize them or not.
Make sure to format the resulting C# files with a formatter or something though

**Review by Speykious — DISMISSED** [review]

**Review by Speykious — APPROVED** [review]
It still doesn't build, but the fix involves changes that would be better off done on PR #9.

**Pull request merged**
