### PR TITLE
Add Unit tests

### PR DESCRIPTION
**Pull request by Speykious**
This pull request adds Unit tests to check that the bindings work correctly.
Like the bindings themselves, they are also ported from the MediapipeUnityPlugin.

### CODE REVIEW

**Review by sr229 — APPROVED** [review]
You fucking madlads you did it.

If this is a dream I don't want to wake up

**Comment by Speykious** [comment]
Me neither lol

**Comment by Speykious** [comment]
The `FloatPacket` which has not yet been ported is being used inside `SidePacketTest.cs`.
If there are any unit tests requiring us to use other objects that we haven't yet ported, we will port them in this pull request to facilitate the flow of development.

**Comment by adryzz** [comment]
I'd say keep the PRs on topic, make a new branch, new PR and then fast forward this branch instead

**Comment by Speykious** [comment]
I said this because we're currently moving quite fast. I'll go to sleep soon as well

**Comment by Speykious** [comment]
I guess I'll see what I can do on the other branch then

**Comment by adryzz** [comment]
Yeah, but if there's any issues later, it'll be better to be organized now.
And yes, i'll probably go to sleep in about an hour too, it's 1AM and i have school tomorrow.

**Comment by Speykious** [comment]
So many things to fix now ._.

**Pull request merged**
