### PR TITLE
Complete C# bindings

### PR DESCRIPTION
**Pull request by Speykious**
The C# bindings have not been fully ported from MediapipeUnityPlugin yet.
This pull request aims at completing them in order to finally have a complete Mediapipe wrapper library.

### CODE REVIEW

**Review by sr229 — APPROVED** [review]

**Comment by Speykious** [comment]
At this stage, Akihabara builds successfully.
image
However, we will need unit tests (in a separate pull request) to make sure that all bindings work correctly.

**Comment by Speykious** [comment]
Also, it seems that the MediapipeUnityPlugin is porting additional classes from Mediapipe that are needed for the specific graphs to be used, namely `instant_motion_tracking` and `object_detection_3d`, 2 graphs that we absolutely don't need for Vignette.
Instead, we would need at least `face_mesh`, and in the future `holistic_tracking` and `hand_tracking`.
Meaning, we will have to figure out how to make our own Bazel targets for these graphs, and put the resulting `.proto` files in the right place.

**Comment by sr229** [comment]
We would love them intact for other consumers too so keep them as-is. Don't just build for our case, since we want this to be used by the greater community.

**Comment by Speykious** [comment]
True ─ we'll get `face_mesh` to work first; when it does, all the others will very likely work with the same process.

**Pull request merged**
