### PR TITLE
Ported last unit tests

### PR DESCRIPTION
**Pull request by Speykious**
These are quite literally the *last* unit tests there are. Every one of them has been ported.

### CODE REVIEW

**Comment by Speykious** [comment]
All the remaining tests that we could possibly want have now been implemented.
However, it won't build. The tests have highlighted some flaws in the porting of MediapipeUnityPlugin, and I intend to fix that in a future PR.

**Review by ym56 — APPROVED** [review]
Looks good to me. Still can't get the tests to work on windows

**Comment by Speykious** [comment]
Yayyy we gucci

**Comment by Speykious** [comment]
Yeah, we'll have to figure out this Windows integration problem.

**Pull request merged**
